// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ4nEouE9MvuOJF2VhfPxSAagh1VwQ4_I',
    appId: '1:267229034807:web:ef34c2f250d61034f402b2',
    messagingSenderId: '267229034807',
    projectId: 'mentalhealthadvisor-9b7c2',
    authDomain: 'mentalhealthadvisor-9b7c2.firebaseapp.com',
    storageBucket: 'mentalhealthadvisor-9b7c2.appspot.com',
    measurementId: 'G-65EXN9C1R0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdzTMBG4h-pvqy2TDbB3Z3h3Wmb0eWI0w',
    appId: '1:267229034807:android:aee3ca470a2754f7f402b2',
    messagingSenderId: '267229034807',
    projectId: 'mentalhealthadvisor-9b7c2',
    storageBucket: 'mentalhealthadvisor-9b7c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChUoIVfLD6kJ_A3LuhO0wKE5lhEHTGZ8E',
    appId: '1:267229034807:ios:548eb61090558bb8f402b2',
    messagingSenderId: '267229034807',
    projectId: 'mentalhealthadvisor-9b7c2',
    storageBucket: 'mentalhealthadvisor-9b7c2.appspot.com',
    iosClientId: '267229034807-e2d9b1tgas2dfnn2kva71ro29j81j9o3.apps.googleusercontent.com',
    iosBundleId: 'com.example.journaler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChUoIVfLD6kJ_A3LuhO0wKE5lhEHTGZ8E',
    appId: '1:267229034807:ios:9dc6ec89918255fdf402b2',
    messagingSenderId: '267229034807',
    projectId: 'mentalhealthadvisor-9b7c2',
    storageBucket: 'mentalhealthadvisor-9b7c2.appspot.com',
    iosClientId: '267229034807-jvncuiqvc68q4ih9hpp5shmgd1m20onc.apps.googleusercontent.com',
    iosBundleId: 'com.example.journaler.RunnerTests',
  );
}
